// Net/SendPackets.h — builders de paquets SORTANTS (C->S) de TwelveSky2.
// GÉNÉRÉ (workflow ts2-net-builders-codegen). Framing sortant + XOR via PacketWriter.
#pragma once
#include "Net/NetClient.h"
#include "Net/Framing.h"
#include "Net/Rng.h"
#include "Net/ClientState.h"

namespace ts2::net {

void Net_SendPacket_Op12(NetClient& nc, const void* head128, const void* name13, const void* tail72);
void Net_SendPacket_Op20(NetClient& nc, int8_t arg1, int8_t arg2);
void Net_SendPacket_Op28(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4);
void Net_SendPacket_Op108(NetClient& nc, int8_t arg1, int8_t arg2, const void* name13);
void Net_SendOp41(NetClient& nc, int8_t arg1);
void Net_SendOp49(NetClient& nc, int8_t arg1);
void Net_SendOp57(NetClient& nc, int8_t arg1);
void Net_SendOp65(NetClient& nc, const void* name13);
void Net_SendOp73(NetClient& nc);
void Net_SendOp81(NetClient& nc, const void* buf61);
void Net_SendOp89(NetClient& nc, int8_t arg1, int8_t arg2);
void Net_SendOp98(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3);
void Net_SendOp105(NetClient& nc);
void Net_SendOp117(NetClient& nc);
void Net_SendOp128(NetClient& nc);
void Net_SendOp138(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7, int8_t arg8, int8_t arg9, int8_t arg10, int8_t arg11, int8_t arg12, int8_t arg13);
void Net_SendVaultReq_203(NetClient& nc, int8_t arg1);
void Net_SendVaultReq_211(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7);
void Net_SendVaultReq_219(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7);
void Net_SendVaultReq_227(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7);
void Net_SendVaultReq_235(NetClient& nc, int8_t arg1);
void Net_SendVaultReq_243(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7);
void Net_SendVaultReq_251(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7);
void Net_SendCmd_247(NetClient& nc, int8_t arg1, int8_t arg2);
void Net_SendCmd_255(NetClient& nc);
void Net_SendCmd_7(NetClient& nc, const void* name13);
void Net_SendCmd_15(NetClient& nc, int8_t arg1);
void Net_SendGuarded_3(NetClient& nc);
void Net_SendGuarded_11(NetClient& nc);
void Net_SendMenu_Var(NetClient& nc, uint8_t opcode);
void Net_SendPacket_Op13(NetClient& nc, int8_t arg);
void Net_SendPacket_Op21(NetClient& nc);
void Net_SendPacket_Op29(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7, int8_t a8, int8_t a9);
void Net_SendPacket_Op109(NetClient& nc, int8_t flag, const void* name13, int8_t b1, int8_t b2, int8_t b3, int8_t b4, int8_t b5, int8_t b6, int8_t b7, const void* blob28);
void Net_SendOp42(NetClient& nc, int8_t a2, int8_t a3, int8_t a4, const void* buf24, int8_t a6);
void Net_SendOp50(NetClient& nc);
void Net_SendOp58(NetClient& nc, int8_t arg);
void Net_SendOp66(NetClient& nc);
void Net_SendOp74(NetClient& nc, int8_t arg);
void Net_SendOp82(NetClient& nc, int8_t a2, int8_t a3);
void Net_SendOp90(NetClient& nc, int8_t a2, int8_t a3);
void Net_SendOp99(NetClient& nc, int8_t a2, const void* appearance68, const void* autoHunt44);
void Net_SendOp106(NetClient& nc, int8_t a2, const void* buf12);
void Net_SendOp116(NetClient& nc);
void Net_SendOp129(NetClient& nc, int8_t a2, int8_t a3);
void Net_SendOp139(NetClient& nc, int8_t arg);
void Net_SendVaultReq_204(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5);
void Net_SendVaultReq_212(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_220(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_228(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_236(NetClient& nc);
void Net_SendVaultReq_244(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_252(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendCmd_248(NetClient& nc, int8_t a1);
void Net_SendCmd_0(NetClient& nc);
void Net_SendCmd_8(NetClient& nc, int8_t a1, int8_t a2);
void Net_SendCmd_16(NetClient& nc, const void* buf12);
void Net_SendGuarded_4(NetClient& nc);
void Net_SendGuarded_12(NetClient& nc);
bool Net_SendUdpReport(uint8_t* self, const char* cp);
void Net_SendPacket_Op14(NetClient& nc, int8_t value);
void Net_SendPacket_Op22(NetClient& nc, int8_t arg0, int8_t arg1);
void Net_SendPacket_Op30(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7, int8_t arg8);
void Net_SendOp110(NetClient& nc, int8_t arg0, int8_t arg1);
void Net_SendOp43(NetClient& nc, const void* payload13, int8_t flag);
void Net_SendOp51(NetClient& nc);
void Net_SendOp59(NetClient& nc, const void* payload13);
void Net_SendOp67(NetClient& nc, int8_t value);
void Net_SendOp75(NetClient& nc, int8_t kind, const void* payload500);
void Net_SendOp83(NetClient& nc, int8_t arg0, int8_t arg1);
void Net_SendOp91(NetClient& nc);
void Net_SendOp101(NetClient& nc);
void Net_SendOp107(NetClient& nc, int8_t kind, const void* payload13);
void Net_SendOp118(NetClient& nc);
void Net_SendOp131(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7, int8_t arg8);
void Net_SendOp140(NetClient& nc);
void Net_SendVaultReq_205(NetClient& nc, int8_t arg0, int8_t arg1);
void Net_SendVaultReq_213(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendVaultReq_221(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendVaultReq_229(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendVaultReq_237(NetClient& nc);
void Net_SendVaultReq_245(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendVaultReq_253(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendCmd_249(NetClient& nc, int8_t arg0);
void Net_SendCmd_1(NetClient& nc, const void* payload13);
void Net_SendCmd_9(NetClient& nc, int8_t arg0);
void Net_SendCmd_17(NetClient& nc, int8_t arg0);
void Net_SendGuarded_5(NetClient& nc, const void* payload204);
void Net_SendGuarded_13(NetClient& nc);
void Net_SendPacket_Op15(NetClient& nc, const void* data72);
void Net_SendPacket_Op23(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3);
void Net_SendPacket_Op31(NetClient& nc, int8_t kind, const void* data1232);
void Net_SendOp36(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5);
void Net_SendOp44(NetClient& nc);
void Net_SendOp52(NetClient& nc);
void Net_SendOp60(NetClient& nc);
void Net_SendOp68(NetClient& nc, const void* data61);
void Net_SendOp76(NetClient& nc, const void* data61);
void Net_SendOp84(NetClient& nc, const void* data101, int8_t flag);
void Net_SendOp92(NetClient& nc, int8_t value);
void Net_SendOp136(NetClient& nc);
void Net_SendOp111(NetClient& nc, int8_t value);
void Net_SendOp119(NetClient& nc);
void Net_SendOp132(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4);
void Net_SendOp141(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, const void* data24);
void Net_SendVaultReq_206(NetClient& nc, int8_t arg1);
void Net_SendVaultReq_214(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7);
void Net_SendVaultReq_222(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7);
void Net_SendVaultReq_230(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7);
void Net_SendVaultReq_238(NetClient& nc);
void Net_SendVaultReq_246(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7);
void Net_SendVaultReq_254(NetClient& nc, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendCmd_250(NetClient& nc, int8_t arg1);
void Net_SendCmd_2(NetClient& nc, const void* data13);
void Net_SendCmd_10(NetClient& nc, int8_t arg1, int8_t arg2);
void Net_SendCmd_18(NetClient& nc, int8_t arg1);
void Net_SendGuarded_6(NetClient& nc);
void Net_SendGuarded_14(NetClient& nc, int8_t arg1);
void Net_SendPacket_Op16(NetClient& nc, const void* payload);
void Net_SendPacket_Op24(NetClient& nc, int8_t a, int8_t b, int8_t c, int8_t d);
void Net_SendPacket_Op32(NetClient& nc, int8_t a);
void Net_SendOp37(NetClient& nc);
void Net_SendOp45(NetClient& nc, int8_t a);
void Net_SendOp53(NetClient& nc, const void* payload);
void Net_SendOp61(NetClient& nc, int8_t a);
void Net_SendOp69(NetClient& nc);
void Net_SendOp77(NetClient& nc, const void* payload);
void Net_SendOp85(NetClient& nc, uint32_t length, const void* data);
void Net_SendOp94(NetClient& nc, const void* data);
void Net_SendOp100(NetClient& nc, int8_t a, int8_t b, const void* data);
void Net_SendOp112(NetClient& nc, const void* payload);
void Net_SendOp120(NetClient& nc, int8_t a, int8_t b, int8_t c);
void Net_SendOp133(NetClient& nc, int8_t a, int8_t b, int8_t c, int8_t d, int8_t e, int8_t f, int8_t g, int8_t h, int8_t i);
void Net_SendOp142(NetClient& nc, int8_t a, int8_t b, int8_t c, int8_t d);
void Net_SendVaultReq_207(NetClient& nc, int8_t amount);
void Net_SendVaultReq_215(NetClient& nc, int8_t npcId, int8_t itemId, int8_t qty, int8_t page, int8_t slot, int8_t col, int8_t row);
void Net_SendVaultReq_223(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_231(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_239(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_247(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_255(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6);
void Net_SendCmd_251(NetClient& nc, const void* data);
void Net_SendCmd_3(NetClient& nc, const void* data);
void Net_SendCmd_11(NetClient& nc, int8_t a, int8_t b);
void Net_SendCmd_19(NetClient& nc, int8_t a);
void Net_SendGuarded_7(NetClient& nc);
void Net_SendGuarded_17(NetClient& nc, const void* data1, const void* data2, int8_t flag);
void Net_SendPacket_Op17(NetClient& nc, const void* payload61);
void Net_SendPacket_Op25(NetClient& nc, int8_t a, int8_t b, int8_t c, int8_t d);
void Net_SendPacket_Op33(NetClient& nc, const void* text13);
void Net_SendOp38(NetClient& nc, const void* payload61);
void Net_SendOp46(NetClient& nc);
void Net_SendOp54(NetClient& nc);
void Net_SendOp62(NetClient& nc);
void Net_SendOp70(NetClient& nc, const void* payload13);
void Net_SendOp78(NetClient& nc, const void* payload13);
void Net_SendOp86(NetClient& nc, int8_t a, int8_t b);
void Net_SendOp95(NetClient& nc, const void* position12, int8_t kind);
void Net_SendOp102(NetClient& nc, int8_t a, int8_t b, int8_t c, int8_t d);
void Net_SendOp113(NetClient& nc, int8_t a);
void Net_SendOp121(NetClient& nc, int8_t a, int8_t b, int8_t c, int8_t d);
void Net_SendOp134(NetClient& nc, int8_t a, int8_t b, int8_t c, int8_t d);
void Net_SendOp143(NetClient& nc, int8_t a, int8_t b, int8_t c);
void Net_SendVaultReq_208(NetClient& nc, int8_t p1, int8_t p2, int8_t p3, int8_t p4, int8_t p5, int8_t p6, int8_t p7);
void Net_SendVaultReq_216(NetClient& nc, int8_t p1, int8_t p2, int8_t p3, int8_t p4, int8_t p5, int8_t p6, int8_t p7);
void Net_SendVaultReq_224(NetClient& nc, int8_t p1, int8_t p2, int8_t p3, int8_t p4, int8_t p5, int8_t p6, int8_t p7);
void Net_SendVaultReq_232(NetClient& nc, int8_t p1, int8_t p2, int8_t p3, int8_t p4, int8_t p5, int8_t p6, int8_t p7);
void Net_SendVaultReq_240(NetClient& nc, int8_t p1, int8_t p2, int8_t p3, int8_t p4, int8_t p5, int8_t p6, int8_t p7);
void Net_SendVaultReq_248(NetClient& nc, int8_t p1, int8_t p2, int8_t p3, int8_t p4, int8_t p5, int8_t p6, int8_t p7);
void Net_SendVaultReq_0(NetClient& nc, int8_t p1, int8_t p2, int8_t p3, int8_t p4, int8_t p5, int8_t p6);
void Net_SendCmd_252(NetClient& nc, int8_t a1);
void Net_SendCmd_4(NetClient& nc, const void* payload13);
void Net_SendCmd_12(NetClient& nc, int8_t a1);
void Net_SendCmd_22(NetClient& nc, int8_t a1);
void Net_SendGuarded_8(NetClient& nc, const void* payload13);
void Net_SendMenu_1(NetClient& nc);
void Net_SendPacket_Op18(NetClient& nc, const void* payload76);
void Net_SendPacket_Op26(NetClient& nc, int8_t f0, int8_t f1, int8_t f2, int8_t f3, int8_t f4);
void Net_SendPacket_Op34(NetClient& nc, int8_t f0, int8_t f1);
void Net_SendOp39(NetClient& nc, const void* target13, const void* message61);
void Net_SendOp47(NetClient& nc, const void* payload13);
void Net_SendOp55(NetClient& nc, int8_t value);
void Net_SendOp63(NetClient& nc);
void Net_SendOp71(NetClient& nc);
void Net_SendOp79(NetClient& nc, int8_t subType, const void* payload100);
void Net_SendOp87(NetClient& nc, int8_t f0, int8_t f1);
void Net_SendOp96(NetClient& nc, int8_t f0, int8_t f1, int8_t f2);
void Net_SendOp103(NetClient& nc, int8_t f0, int8_t f1, int8_t f2);
void Net_SendOp114(NetClient& nc, int8_t f0, int8_t f1, int8_t f2);
void Net_SendOp126(NetClient& nc, int8_t value);
void Net_SendOp135(NetClient& nc, int8_t f0, int8_t f1, int8_t f2, int8_t f3, int8_t f4, int8_t f5, int8_t f6, int8_t f7, int8_t f8);
void Net_SendVaultReq_201(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_209(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_217(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_225(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_233(NetClient& nc, int8_t a1, int8_t a2);
void Net_SendVaultReq_241(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_249(NetClient& nc, int8_t a1, int8_t a2, int8_t a3, int8_t a4, int8_t a5, int8_t a6, int8_t a7);
void Net_SendVaultReq_245b(NetClient& nc);
void Net_SendCmd_253(NetClient& nc);
void Net_SendCmd_5(NetClient& nc, const void* payload13);
void Net_SendCmd_13(NetClient& nc, int8_t value);
void Net_SendGuarded_1(NetClient& nc, const void* payload13);
void Net_SendGuarded_9(NetClient& nc, const void* payload13, int8_t value);
void Net_SendMenu_2(NetClient& nc, const void* payload13);
void Net_SendPacket_Op19(NetClient& nc, uint8_t subCmd, const void* payload);
void Net_SendPacket_Op27(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3);
void Net_SendPacket_Op35(NetClient& nc, int8_t flag, const void* name13, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendOp40(NetClient& nc, const void* payload61);
void Net_SendOp48(NetClient& nc);
void Net_SendOp56(NetClient& nc, int8_t arg0);
void Net_SendOp64(NetClient& nc);
void Net_SendOp72(NetClient& nc, const void* payload13);
void Net_SendOp80(NetClient& nc, const void* chatMsg61);
void Net_SendOp88(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6, int8_t arg7, int8_t arg8);
void Net_SendOp97(NetClient& nc, int8_t arg0);
void Net_SendOp104(NetClient& nc, int8_t arg0, int8_t arg1);
void Net_SendOp115(NetClient& nc, int8_t arg0);
void Net_SendOp127(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3);
void Net_SendOp137(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3);
void Net_SendVaultReq_202(NetClient& nc, int8_t arg0, int8_t arg1);
void Net_SendVaultReq_210(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendVaultReq_218(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendVaultReq_226(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendVaultReq_234(NetClient& nc, int8_t arg0);
void Net_SendVaultReq_242(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendVaultReq_250(NetClient& nc, int8_t arg0, int8_t arg1, int8_t arg2, int8_t arg3, int8_t arg4, int8_t arg5, int8_t arg6);
void Net_SendCmd_246(NetClient& nc);
void Net_SendCmd_254(NetClient& nc, int8_t arg0);
void Net_SendCmd_6(NetClient& nc, const void* data13);
void Net_SendCmd_14(NetClient& nc);
void Net_SendGuarded_2(NetClient& nc, int32_t ctxId);
void Net_SendGuarded_10(NetClient& nc, const void* data13, const void* data5);
void Net_SendMenu_3(NetClient& nc, const void* data13);

} // namespace ts2::net
