// Gfx/EquipModelResolver.h — resolves player equipment to a STEM.
//
// Two distinct resolutions, proven in IDA (sole source of truth, IDB RE/TwelveSky2.exe.i64):
//
//   (A) Equipment MODEL (paperdoll) -> SObject stem consumable by ModelCache::Get.
//       Faithful port of SObject_BuildPath 0x4D89C0: families W(eapon)/L/H/A/P + body parts
//       (slots 14..21 + 0/1/2 of the mega-switch case 1). Each stem = "C…/W…/L…/H…/A…/P…"
//       (prefix = 1st letter, cf. ModelCache::ResolveSObjectFolder).
//
//   (B) Weapon MOTION (shared bone palette) -> MOTION slot + stem "C…/X….MOTION".
//       Faithful port of the PcModel_ResolveEquipSlot 0x4E46A0 mega-switch (item id ranges ->
//       weapon animation family). Consumable by MotionCache (NOT ModelCache).
//
// ─────────────────────────────────────────────────────────────────────────────────────────────
//  MAJOR CORRECTION (proven here — CONTRADICTS the T3 hypothesis of Docs/TS2_DEEP_SOBJECT.md §3/§6)
// ─────────────────────────────────────────────────────────────────────────────────────────────
//  T3 assumed that PcModel_ResolveEquipSlot 0x4E46A0 maps an item id -> a paperdoll SObject MODEL
//  in a pre-generated catalog. THAT IS WRONG. The derivation requested by the task (via
//  AssetMgr_InitAllSlots 0x4DEB50, same method as the monster catalog flt_FBBF3C/flt_FF67CC)
//  proves that the returned pointer indexes the **MOTION** catalog (156-byte entries), NOT the
//  SObject catalog (144-byte entries):
//
//    return = g_ModelMotionArray(0x8E8B30) + 479232·race + 159744·gender + 19968·f2 + 156·f3 + base
//      base 2624960 (0x280F40) == Motion_BuildPathAndLoad loop, AssetMgr **category 1**
//                                 (this + 479232·i10 + 159744·i11 + 19968·i12 + 156·i13 + 2624960)
//                                 -> player body, "D03_GMOTION\001\C%03d%03d%03d.MOTION"
//      base 4062656 (0x3DFF40) == Motion_BuildPathAndLoad loop, AssetMgr **category 6**
//                                 (this + 479232·i25 + 159744·i26 + 19968·i27 + 156·i28 + 4062656)
//                                 -> weapon, "D03_GMOTION\006\X%03d%03d%03d.MOTION"
//    stride 156 == size of a MOTION entry (cf. MotionCache.h: "g_ModelMotionArray 0x8E8B30,
//    156-byte entries each"). The SObject catalog uses 144 (all AssetMgr SObject_BuildPath
//    loops) -> incompatible.
//
//  Confirmed by the CONSUMER: Char_RenderModel 0x527020 does
//    v37 = PcModel_ResolveEquipSlot(g_ModelMotionArray, race, gender, f2, f3, 1, 0, 0);
//  then passes v37 as the 7th argument (bone palette) to EVERY paperdoll SObject_DrawEx call
//  (PlayerPaperdoll.h: "v37 = … = ONE bone palette shared by ALL pieces"). v37 is therefore a
//  MOTION, not a model. MotionCache.h §33 already documents 0x4E46A0 as the player palette
//  resolver — this correction generalizes it to the mega-switch (weapon id ranges).
//
// ─────────────────────────────────────────────────────────────────────────────────────────────
//  ACTUAL RESOLUTION OF THE EQUIPMENT MODEL (Char_RenderModel 0x527020 — the real table)
// ─────────────────────────────────────────────────────────────────────────────────────────────
//  An equipment piece's model is NOT resolved by 0x4E46A0. It is resolved like this:
//    itemRec    = MobDb_GetEntry(&mITEM, equippedItemId);   // item's ITEM_INFO record
//    modelIndex = *(itemRec + 196);                         // field +196 = visual MODEL INDEX
//    desc       = flt_F5xxxx[strideRace·race + strideGender·gender + 36·modelIndex]; // 36 floats=144 B
//  where flt_F5xxxx is a SObject catalog pre-generated by AssetMgr_InitAllSlots (SObject_BuildPath).
//  Example (helmet, v29=a4[34]): flt_F6685C[3672·race + 1836·gender + 36·*(v29+196)]
//    = byte offset 14688·race + 7344·gender + 144·modelIndex  ==  AssetMgr case 1 / slot 14 loop
//      (SObject_BuildPath(…, 1, race, gender, 14, i-1, 0), i<51)  ->  "C%03d003%03d".
//  => a body piece's STEM = BuildArmorBodyStem(race, gender, slot, modelIndex) below;
//     the "item id -> modelIndex" link = ITEM_INFO field +196 (anchor 0x527020, MobDb_GetEntry).
//
//  This module stays SELF-CONTAINED: it does not read the item database itself — the caller
//  supplies `modelIndex` (= ITEM_INFO+196). No wiring, no project dependency (pure stems).
//
// TODO anchor (NOT statically derivable from this front — see §7 of Docs/TS2_DEEP_SOBJECT.md):
//   - Full mapping "paperdoll slot (a4[30..74]) -> flt_F5xxxx catalog -> (category, bodySlot)"
//     for the ~9 Char_RenderModel slots: only the BODY slots (0/1/2/14..21) and the weapon are
//     derived here. The other catalogs (flt_100EA3C weapon, unk_F86CBC capes,
//     flt_FABEBC/flt_FB7BBC via *(Entry+188), …) require tracing each base individually.
//   - Weapon model sub-selection `v26` (Char_RenderModel: Item_GetAttribByte0 0x545610 /
//     Item_ClassifyById 0x550800 -> index 0..8): logic driven by intertwined item attributes,
//     left to a dedicated front.
//
// Anchors: SObject_BuildPath 0x4D89C0 ; PcModel_ResolveEquipSlot 0x4E46A0 ;
//          Motion_IsValidWeaponPose 0x4E3A30 ; AssetMgr_InitAllSlots 0x4DEB50 ;
//          Motion_BuildPathAndLoad 0x4D7390 ; Char_RenderModel 0x527020 ;
//          g_ModelMotionArray 0x8E8B30.
#pragma once
#include <cstdint>
#include <string>

namespace ts2::gfx {

// ─────────────────────────────────────────────────────────────────────────────
//  (A) SObject MODEL STEMS — faithful port of SObject_BuildPath 0x4D89C0.
// ─────────────────────────────────────────────────────────────────────────────

// SObject category (2nd arg `a2` of SObject_BuildPath 0x4D89C0 @0x4d89e5). The numeric values
// ARE those from the binary (prefix/folder inferred — see comments).
enum class SObjectEquipCategory : int {
    PlayerBody = 1, // "C…" 001  (body + body parts; see BuildArmorBodyStem for slots)
    P          = 4, // "P%03d%03d%03d" 004
    L          = 5, // "L%03d%03d%03d" 005  (kind = race+3·gender+1)
    Weapon     = 6, // "W%03d%03d%03d%03d" 006  (weapon; 4 indices)
    H          = 7, // "H%03d%03d%03d" 007
    Y          = 9, // "Y%03d%03d" 009
    LSet2      = 10, // "L%03d%03d%03d" 005  (kind = race+3·gender+7)
    A_001      = 11, // "A%03d001%03d" 010  (kind = race+3·gender+1)
    A_004      = 12, // "A%03d004%03d" 010  (kind = race+3·gender+1)
    A_001Set2  = 13, // "A%03d001%03d" 010  (kind = race+3·gender+7)
    A_004Set2  = 14, // "A%03d004%03d" 010  (kind = race+3·gender+7)
};

// Player body-part slot — `a5` selector of SObject_BuildPath case 1 (switch @0x4d8a08).
// The middle token (003/004/…) and the kind offset (+1 or +7) come from the binary (format
// strings @0x4d8a30..0x4d8baf). Slots 0/1/2 fall into the default case (token = slot+1).
enum class EquipBodySlot : int {
    Base0    = 0,  // "C%03d001%03d"  kind+1  (body SLOT0, flt_F59A7C)
    Base1    = 1,  // "C%03d002%03d"  kind+1  (body SLOT1, flt_F5B21C)
    Base2    = 2,  // "C%03d003%03d"  kind+1  (unk_F5BC3C; default, token=slot+1)
    Slot14   = 14, // "C%03d003%03d"  kind+7  (flt_F6685C)
    Slot15   = 15, // "C%03d004%03d"  kind+7  (flt_F7C09C)
    Slot16   = 16, // "C%03d014%03d"  kind+7
    Slot17   = 17, // "C%03d012%03d"  kind+7
    Slot18   = 18, // "C%03d013%03d"  kind+7
    Slot19   = 19, // "C%03d008%03d"  kind+7
    Slot20   = 20, // "C%03d015%03d"  kind+1
    Slot21   = 21, // "C%03d016%03d"  kind+1
};

// 1:1 port of SObject_BuildPath 0x4D89C0 (STEM part: filename WITHOUT folder or ".SOBJECT").
// `a3`=race, `a4`=gender (other indices depend on category, see .cpp table). Empty string if
// the category is unknown (default branch @0x4d8df9) or if race/gender are out of [0,3)/[0,2).
// For category PlayerBody, prefer BuildArmorBodyStem (handles the per-slot middle token).
std::string BuildSObjectStem(SObjectEquipCategory cat, int a3, int a4, int a5, int a6 = 0, int a7 = 0);

// Body piece (paperdoll): "C{kind:03d}{token:03d}{variant+1:03d}" (SObject_BuildPath case 1).
// kind = race+3·gender (+1 or +7 depending on slot, see EquipBodySlot). `variant` = visual model
// index = ITEM_INFO+196 for an equipment piece (anchor Char_RenderModel 0x527020), or the costume
// index for the base body (slots 0/1). Empty string if race/gender out of bounds ([0,3)/[0,2))
// or variant < 0. (Note: the binary does not bound-check `variant` — the caller guarantees the
// file exists on disk.)
std::string BuildArmorBodyStem(int race, int gender, EquipBodySlot slot, int variant);

// Weapon (paperdoll): "W{race+3·gender+1:03d}{type+1:03d}{subType+1:03d}{level+1:03d}"
// (SObject_BuildPath case 6 @0x4d8ca0). Empty string if race/gender out of bounds or indices < 0.
std::string BuildWeaponStem(int race, int gender, int type, int subType, int level);

// ─────────────────────────────────────────────────────────────────────────────
//  (B) WEAPON MOTION SLOT/STEM — faithful port of PcModel_ResolveEquipSlot 0x4E46A0.
// ─────────────────────────────────────────────────────────────────────────────

// Decodes the PcModel_ResolveEquipSlot 0x4E46A0 return pointer into MOTION catalog indices
// (see header banner for the offset-decomposition proof). `field2`/`field3` are the indices as
// they feed into the MOTION path (Motion_BuildPathAndLoad 0x4D7390):
//   category 1 -> "C%03d%03d%03d" % (race+3·gender+1, field2+1, field3+1)
//   category 6 -> "X%03d%03d%03d" % (race+3·gender+1, field2+1, field3+1)
struct EquipMotionSlot {
    bool valid       = false; // false = entry guard 0x4e46cc failed (invalid pose) -> sentinel
    int  motionCat   = 0;     // 1 (player body, base 2624960) or 6 (weapon, base 4062656)
    int  race        = 0;     // a2 (0..2)
    int  gender      = 0;     // a3 (0..1)
    int  field2      = 0;     // stride 19968: "pose" (a4), OR 0 for the switch's fixed slots
    int  field3      = 0;     // stride 156: "state/type" (a5), OR fixed anim index (77/84/100..127)
};

// Faithful port of the PcModel_ResolveEquipSlot 0x4E46A0 mega-switch: maps the equipped weapon id
// `itemId` (a8) + race/gender + pose(a4)/state(a5) + a6/a7 to the corresponding MOTION slot.
// Reproduces exactly the entry guard (Motion_IsValidWeaponPose 0x4E3A30) and every branch of the
// id switch (ranges 510/559/814..821/1301..2489/19002..19280…). Returns {valid=false} for the
// entry sentinel (return `this + 2644772` == cat 1, race0/gender0, field3=127).
EquipMotionSlot ResolveWeaponMotionSlot(int itemId, int race, int gender,
                                        int a4_pose, int a5_state, int a6 = 1, int a7 = 0);

// MOTION stem of the resolved slot: "C{…}" (cat 1) or "X{…}" (cat 6), WITHOUT folder or ".MOTION".
// Meant for MotionCache (folder D03_GMOTION\001 or \006), NOT ModelCache. Empty string if the slot
// is invalid or out of bounds. (Special case anim==120 of Motion_BuildPathAndLoad case 1 NOT
// reproduced here: field3 is already a resolved anim index, never 120 in the switch's returns.)
std::string BuildWeaponMotionStem(const EquipMotionSlot& slot);

} // namespace ts2::gfx
